package com.example.news.ui.fragments

import android.content.res.ColorStateList
import android.graphics.Color
import android.os.Bundle
import android.view.View
import android.webkit.WebViewClient
import androidx.fragment.app.Fragment
import androidx.navigation.fragment.navArgs
import com.example.news.R
import com.example.news.db.Article
import com.example.news.ui.NewsActivity
import com.example.news.ui.NewsViewModel
import com.google.android.material.snackbar.Snackbar
import kotlinx.android.synthetic.main.fragment_article.*

class ArticleFragment:Fragment(R.layout.fragment_article) {

    lateinit var viewModel : NewsViewModel
    // ArticleFragmentArgs class is generated by android when we add argument to our nav graph.
    val args: ArticleFragmentArgs by navArgs()
    var fabHeartColor = false

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        viewModel = (activity as NewsActivity).viewModel
        val article = args.article
        webView.apply {
            webViewClient = WebViewClient()     // this make sure that the webView opens inside
                                                // android device and not in the browser.

            article.url?.let { loadUrl(it) }
        }
        fab.setOnClickListener {
            viewModel.saveArticle(article)
            fabHeartColor=true
            Snackbar.make(view,"Article saved successfully.",Snackbar.LENGTH_LONG).show()
            if(fabColor()) {
                fab.imageTintList= ColorStateList.valueOf(Color.rgb(255, 50, 50))
                fabHeartColor=false
            }
        }
    }

    fun fabColor(): Boolean = fabHeartColor

}